Repository tuist/Noora, pull requests merged in 2025-03, with the labels that each got.

#194 feat: add support for logging using swift-log
  .github/workflows/noora.yml
  Package.resolved
  Package.swift
  Sources/Noora/Components/Alert.swift
  Sources/Noora/Components/CollapsibleStep.swift
  Sources/Noora/Components/ProgressStep.swift
  Sources/Noora/Components/SingleChoicePrompt.swift
  Sources/Noora/Components/TextPrompt.swift
  Sources/Noora/Components/YesOrNoChoicePrompt.swift
  Sources/Noora/Noora.swift
  Sources/Noora/NooraMock.swift
  Sources/Noora/Utilities/TerminalText.swift
  Tests/NooraTests/Components/CollapsibleStepTests.swift
  Tests/NooraTests/Components/CompletionTests.swift
  Tests/NooraTests/Components/ProgressStepTests.swift
  Tests/NooraTests/Components/SingleChoicePromptTests.swift
  Tests/NooraTests/Components/TextPromptTests.swift
  Tests/NooraTests/Components/YesOrNoChoicePromptTests.swift
  mise/tasks/build
  mise/tasks/build-spm
  mise/tasks/test
  mise/tasks/test-spm
Labels: size:L, lgtm

#214 fix: component overriding previous renders
  Sources/Noora/Noora.swift
  Sources/Noora/NooraMock.swift
Labels: changelog:fixed, size:M, lgtm

#216 fix: improve contrast of secondary, accent, and success colors in the default theme.
  Sources/Noora/Theme.swift
Labels: size:XS, lgtm

#217 fix: recursion in the extension to render single choice prompt component
  Sources/Noora/Noora.swift
  Sources/Noora/NooraMock.swift
  Tests/NooraTests/Components/SingleChoicePromptTests.swift
  Tests/NooraTests/Utilities/TerminalTextTests.swift
Labels: changelog:fixed, size:M, lgtm

#218 fix: infinite recursion when rendering the yes-or-no-choice-prompt and text-prompt components
  Sources/Noora/Noora.swift
Labels: changelog:fixed, size:S, lgtm

#226 feat: make alerts hashable
  Sources/Noora/Noora.swift
Labels: enhancement, size:XS, lgtm

#227 feat: make alert properties public
  Sources/Noora/Noora.swift
Labels: enhancement, size:S, lgtm

#228 fix: handle multi-line texts in alerts
  Sources/Noora/Components/Alert.swift
Labels: changelog:fixed, size:S, lgtm

#230 fix: improve the copy of the warning alert
  Sources/Noora/Components/Alert.swift
  Tests/NooraTests/Components/CompletionTests.swift
Labels: changelog:fixed, size:XS, lgtm

#233 feat: add support for resetting NooraMock's data
  Sources/Noora/NooraMock.swift
Labels: enhancement, size:XS, lgtm

#240 feat: add progress bar step component
  Sources/Noora/Components/ProgressBarStep.swift
  Sources/Noora/Noora.swift
  Sources/Noora/NooraMock.swift
  Sources/examples-cli/Commands/ProgressBarStepCommand.swift
  Sources/examples-cli/ExamplesCLI.swift
  Tests/NooraTests/Components/ProgressBarStepTests.swift
  Tests/NooraTests/Mocks/MockSpinner.swift
  docs/.vitepress/config.mjs
  docs/content/components/step/progress-bar.md
  docs/content/public/components/step/progress-bar/interactive.gif
  docs/content/public/components/step/progress-bar/non-interactive.gif
Labels: documentation, enhancement, size:XL, lgtm

#250 feat: support path components in TerminalText
  Package.resolved
  Package.swift
  Sources/Noora/Utilities/TerminalText.swift
Labels: enhancement, size:S, lgtm
